# Site settings
title: sezznb
email: sejinnnnnn2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  컴공 4학년 입니다 ^~^
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://sejinnnnnn.github.io
twitter_username: twitter_username
github_username:  sejinnnnnn

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


